version: '3.8'

services:
  app:
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - .env.prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: npm run start
